version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ticketsdb
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
